server.port=8080
spring.application.name=api-gateway

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.jersey.enabled=false
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.cloud.gateway.server.webmvc.routes[0].id=account-service-route
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://account-service
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/accounts/**

spring.cloud.gateway.server.webmvc.routes[1].id=ride-service-route
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ride-service
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/rides/**
