server.port=8082
spring.application.name=ride-service

spring.datasource.url=jdbc:postgresql://localhost:5433/pge_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.jersey.enabled=false
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.cloud.openfeign.client.config.default.connect-timeout=5000
spring.cloud.openfeign.client.config.default.read-timeout=5000