spring.application.name=account-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/pge_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.jersey.enabled=false
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false